### PR TITLE
Add piechart data import via parameter and color support

### PR DESCRIPTION
**Pull request by FWirtz**
Add color support: Color can be supplied by an array of strings.
Also fix data loading via parameters of component. Works well now.

~~~resize diagram dynamically -> will be done in master~~~

see #9

### CODE REVIEW

**Comment by FWirtz** [comment]
:-1:

**Comment by FWirtz** [comment]
TODO
- [ ] check @Langleu commit 463b155

**Comment by Langleu** [comment]
👍

**Comment by FWirtz** [comment]
:+1:

**Comment by FWirtz** [comment]
:+1:

**Comment by Langleu** [comment]
👍

**Pull request merged**
